from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={'db_table': 'role'},
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.IntegerField(default=1)),
                ('role', models.ForeignKey(null=True, blank=True, on_delete=models.deletion.SET_NULL, to='accounts.role', db_column='role_id')),
            ],
            options={'db_table': 'user'},
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=150, unique=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={'db_table': 'brand'},
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('perfume_id', models.AutoField(primary_key=True, serialize=False)),
                ('perfume_name', models.CharField(max_length=200)),
                ('concentration', models.CharField(max_length=50)),
                ('top_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('base_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('longevity_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sillage', models.CharField(blank=True, max_length=20, null=True)),
                ('recommended_season', models.CharField(blank=True, max_length=100, null=True)),
                ('target_gender', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(null=True, blank=True, on_delete=models.deletion.SET_NULL, to='accounts.brand', db_column='brand_id')),
            ],
            options={'db_table': 'perfume'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=20)),
                ('volume_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('perfume', models.ForeignKey(null=True, blank=True, on_delete=models.deletion.SET_NULL, to='accounts.perfume', db_column='perfume_id')),
            ],
            options={'db_table': 'product'},
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=100, default='Bangladesh')),
                ('is_default', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, to='accounts.user', db_column='user_id')),
            ],
            options={'db_table': 'address'},
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, to='accounts.user', db_column='user_id')),
            ],
            options={'db_table': 'cart'},
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.cart', db_column='cart_id')),
                ('product', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.product', db_column='product_id')),
            ],
            options={'db_table': 'cart_item'},
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50, default='Pending')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, blank=True, on_delete=models.deletion.SET_NULL, to='accounts.user', db_column='user_id')),
                ('address', models.ForeignKey(null=True, blank=True, on_delete=models.deletion.SET_NULL, to='accounts.address', db_column='address_id')),
            ],
            options={'db_table': 'customer_order'},
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.customerorder', db_column='order_id')),
                ('product', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.product', db_column='product_id')),
            ],
            options={'db_table': 'order_item'},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=20, default='Pending')),
                ('order', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.customerorder', db_column='order_id')),
            ],
            options={'db_table': 'payment'},
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, default=0)),
                ('status', models.CharField(max_length=20, default='Issued')),
                ('order', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.customerorder', db_column='order_id')),
            ],
            options={'db_table': 'invoice'},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified_purchase', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.user', db_column='user_id')),
                ('product', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.product', db_column='product_id')),
            ],
            options={'db_table': 'review'},
        ),
        migrations.CreateModel(
            name='BulkBottle',
            fields=[
                ('bottle_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('bottle_size_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ml_remaining', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('authenticity_verified', models.IntegerField(default=0)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('perfume', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.perfume', db_column='perfume_id')),
            ],
            options={'db_table': 'bulk_bottle'},
        ),
        migrations.CreateModel(
            name='DecantBatch',
            fields=[
                ('decant_batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_created', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bottle', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.bulkbottle', db_column='bottle_id')),
                ('product', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.product', db_column='product_id')),
            ],
            options={'db_table': 'decant_batch'},
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={'db_table': 'faq'},
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.user', db_column='user_id')),
            ],
            options={'db_table': 'password_reset_token'},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('table_affected', models.CharField(max_length=100)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, blank=True, on_delete=models.deletion.SET_NULL, to='accounts.user', db_column='user_id')),
            ],
            options={'db_table': 'audit_log'},
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_used', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=45)),
                ('was_successful', models.IntegerField()),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={'db_table': 'login_attempt'},
        ),
        migrations.CreateModel(
            name='ChatbotLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, blank=True, on_delete=models.deletion.SET_NULL, to='accounts.user', db_column='user_id')),
            ],
            options={'db_table': 'chatbot_log'},
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.user', db_column='user_id')),
                ('product', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.product', db_column='product_id')),
            ],
            options={'db_table': 'wishlist'},
        ),
    ]
